apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: postgres
    prometheus.io/path: /
    prometheus.io/port: "5432"
    prometheus.io/scrape: "true"
  labels:
    app: postgres
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        app: postgres
        prometheus.io/path: /
        prometheus.io/port: "5432"
        prometheus.io/scrape: "true"
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 45
      containers:
        - env:
            - name: POSTGRES_DB
              value: bookstore
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: newuser
          image: postgres:latest
          imagePullPolicy: Always
          name: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
