apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5432"
    prometheus.io/path: "/"
    app: postgres
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5432"
        prometheus.io/path: "/"
        app: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: bookstore
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: newuser
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-data
          restartPolicy: Always
          volumes:
            - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data

        # - name: postgres-exporter
        #   image: prometheuscommunity/postgres-exporter:v0.15.0
        #   imagePullPolicy: IfNotPresent
        #   ports:
        #     - containerPort: 9187
        #   env:
        #     - name: DATA_SOURCE_URI
        #       value: postgres://newuser:password@localhost:5432/bookstore?sslmode=disable
        #   resources:
        #     requests:
        #       cpu: 50m
        #       memory: 32Mi
        #     limits:
        #       cpu: 200m
        #       memory: 64Mi

status: {}
