apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: postgres
    prometheus.io/path: /
    prometheus.io/port: "5432"
    prometheus.io/scrape: "true"
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app: postgres
        prometheus.io/path: /
        prometheus.io/port: "5432"
        prometheus.io/scrape: "true"
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: bookstore
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: newuser
          image: postgres:latest
          imagePullPolicy: Always
          name: postgres
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
