apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: react-app
  labels:
    app: react-app
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      annotations:
        app: react-app
      creationTimestamp: null
      labels:
        app: react-app
    spec:
      containers:
        - image: bookstore-react-react-app:latest
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          name: react-app-container
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 514Mi
            requests:
              cpu: 100m
              memory: 256Mi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
      restartPolicy: Always
      volumes: null
