apiVersion: v1
kind: Service
metadata:
  annotations:
    application: react-app
  labels:
    app: react-app
  name: react-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: react-app
