apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: react-app
  labels:
    app: react-app
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  strategy: {}
  template:
    metadata:
      annotations:
        app: react-app
      creationTimestamp: null
      labels:
        app: react-app
    spec:
      containers:
        image: bookstore-react-react-app:latest
        imagePullPolicy: Never
        name: react-app-container
        ports:
          - containerPort: 8080
            name: http
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 514Mi
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
