apiVersion: v1
kind: Service
metadata:
  annotations:
    application: spring-app
  labels:
    app: spring-app
  name: spring-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: spring-app
status:
  loadBalancer: {}
